<?php

namespace Liveet\Domain;

class Constants
{
  const PRODUCTION_HOST = "https://api.liveet.co";

  const ENVIRONMENT_DEVELOPMENT = "development";

  const USERTYPE_ADMIN = "ADMIN";
  const USERTYPE_ORGANISER_ADMIN = "ORGANIZER_ADMIN";
  const USERTYPE_ORGANISER_STAFF = "ORGANIZER_STAFF";
  const USERTYPE_USER = "USER";

  const USER_NOT_VERIFIED = 0;
  const USER_VERIFIED = 1;
  const EMAIL_NOT_VERIFIED = 0;
  const EMAIL_VERIFIED = 1;

  const USER_ENABLED = "ENABLED";
  const USER_DISABLED = "DISABLED";

  const DEFAULT_RESET_PASSWORD = "Liveet_12345";

  const PRIVILEDGE_ADMIN_EVENT = "EVENT";
  const PRIVILEDGE_ADMIN_ORGANISER = "ORGANISER";
  const PRIVILEDGE_ADMIN_ACTIVITY_LOG = "ACTIVITY_LOG";
  const PRIVILEDGE_ADMIN_REPORT = "REPORT";
  const PRIVILEDGE_ADMIN_ADMIN = "ADMIN";
  const PRIVILEDGE_ADMIN_PAYMENT = "PAYMENT";
  const PRIVILEDGE_ADMIN_USER = "USER";
  const PRIVILEDGE_ADMIN_FACE_VERIFICATION_LOG = "FACE_VERIFICATION_LOG";
  const PRIVILEDGE_ADMIN_TURNSTILE = "TURNSTILE";

  const PRIVILEDGE_ORGANISER_EVENT = "EVENT";
  const PRIVILEDGE_ORGANISER_ORGANISER = "ORGANISER";
  const PRIVILEDGE_ORGANISER_ACTIVITY_LOG = "ACTIVITY_LOG";
  const PRIVILEDGE_ORGANISER_REPORT = "REPORT";
  const PRIVILEDGE_ORGANISER_PAYMENT = "PAYMENT";
  const PRIVILEDGE_ORGANISER_USER = "USER";
  const PRIVILEDGE_ORGANISER_FACE_VERIFICATION_LOG = "FACE_VERIFICATION_LOG";
  const PRIVILEDGE_ORGANISER_TURNSTILE = "TURNSTILE";

  const ERROR_NOT_FOUND = "Not found";
  const ERROR_EMPTY_DATA = "No more data";

  const IMAGE_PATH = "assets/images/";
  const IMAGE_TYPES_ACCEPTED = ["jpg", "png", "gif", "bmp", "jpeg"];
  const VIDEO_PATH = "assets/videos/";
  const VIDEO_TYPES_ACCEPTED = ["mp4", "avi", "flv", "mov"];
  const MEDIA_PATH = "assets/medias/";
  const MEDIA_TYPES_ACCEPTED = ["pdf"];

  const MEDIA_TYPES = ["IMAGE", "VIDEO", "APPLICATION"];

  const MEDIA_TYPE_IMAGE = "IMAGE";
  const MEDIA_TYPE_VIDEO = "VIDEO";
  const MEDIA_TYPE_APPLICATION = "APPLICATION";
  const MEDIA_TYPE_PDF = "PDF";

  /**
   * value "local" | "s3Bucket" | "azure"
   */
  const CDN = ["local" => "handleParseMedia", "s3Bucket" => "handleS3ParseMedia", "azure" => "handleAzureParseMedia"];

  const IMAGE_RESIZE_MAX_WIDTH = 1200;
  const IMAGE_RESIZE_MAX_HEIGHT = 1200;
  const IMAGE_RESIZE_QUALITY = 90;

  const AWS_S3_BASE_URL = "https://liveet-prod-media.s3-us-west-2.amazonaws.com/";

  const EVENT_ACCESS_ASSIGNED = "ASSIGNED";
  const EVENT_ACCESS_UNASSIGNED = "UNASSIGNED";
  const EVENT_ACCESS_USED = "USED";

  const EVENT_CAN_TRANSFER_TICKET = "CAN_TRANSFER";
  const EVENT_CAN_NOT_TRANSFER_TICKET = "CAN_NOT_TRANSFER";
  const EVENT_CAN_RECALL_TICKET = "CAN_RECALL";
  const EVENT_CAN_NOT_RECALL_TICKET = "CAN_NOT_RECALL";
  const EVENT_CAN_INVITE = "CAN_INVITE";
  const EVENT_CAN_INVITE_RESTRICTED = "CAN_INVITE_RESTRICTED";
  const EVENT_CAN_NOT_INVITE = "CAN_NOT_INVITE";

  const EVENT_TICKET_USED = "TICKET_USED";
  const EVENT_TICKET_UNUSED = "TICKET_UNUSED";

  const INVITATION_ACCEPT = "ACCEPTED";
  const INVITATION_DECLINED = "DECLINED";
  const INVITATION_PENDING = "PENDING";

  const PAYMENT_TYPE_FREE = "FREE";
  const PAYMENT_TYPE_PAID = "PAID";

  const EVENT_TYPE_PRIVATE = "PRIVATE";
  const EVENT_TYPE_PUBLIC = "PUBLIC ";

  const CREATE_AWS_EVENT_RETRY = 3;

  const INVITEE_CAN_INVITE = "INVITEE_CAN_INVITE";
  const INVITEE_CAN_NOT_INVITE = "INVITEE_CAN_NOT_INVITE";

  const EVENT_TICKET_TRANSFERRED = "TRANSFERRED";
  const EVENT_TICKET_RECALLED = "RECALLED";
  const EVENT_TICKET_ACTIVE = "ACTIVE";

  const NOTIFICATION_ALL_USER = "ALL_USER";
  const NOTIFICATION_ONE_USER = "ONE_USER";
  const NOTIFICATION_USER_GROUP = "USER_GROUP";


  const MOBILE_APP_DOWNLOAD_URL = "https://liveet.co";

  const TIMELINE_NOTIFICATION_TITLE = "Timeline";
  const TIMELINE_NOTIFICATION_MESSAGE = "A new timeline was uploaded";

  //User Activity Types
  const LOG_GET_EVENTS = "GET EVENTS";
  const LOG_SET_FAVOURITE = "SET FAVOURITE";
  const LOG_GET_TICKET = "GET TICKETS";
  const LOG_ATTEND_EVENT = "ATTEND EVENT";
  const LOG_CHECK_PAYMENT = "CHECK PAYMENT";
  const LOG_GET_FAVOURITE = "GET FAVOURITE";
  const LOG_GET_EVENTS_ACCESS = "GET EVENTS FROM ACCESS";
  const LOG_DELETE_INVITATION = "DEL INVITATION";
  const LOG_SEND_INVITATION = "SEND INVITATION";
  const LOG_GET_EVENT_HISTORY = "GET EVENT HISTORY";
  const LOG_RECALL_TICKET = "RECALL TICKET";
  const LOG_TRANSFER_TICKET = "TRANSFER TICKET";
  const LOG_GET_TIMELINE = "GET TIMELINE";

  //face verification type
  const VERIFICATION_VERIFIED = "VERIFIED";
  const VERIFICATION_FAILED = "FAILED";

  //User Reg Status
  const USER_REG_NOTCOMPLETED = "NOT_COMPLETED";
  const USER_REG_COMPLETED = "COMPLETED";
}
