<?php

namespace Liveet\Domain;

class Constants
{
  const PRODUCTION_HOST = "https://api.liveet.co";
  const DEVELOPMENT_HOST = "localhost";
  // const DEVELOPMENT_BASE_PATH = "/liveet/liveet-apis";
  // const PRODUCTION_BASE_PATH = "/liveet";

  const ENVIRONMENT_DEVELOPMENT = "development";

  const USERTYPE_ADMIN = "ADMIN";
  const USERTYPE_ORGANISER_ADMIN = "ORGANIZER_ADMIN";
  const USERTYPE_ORGANISER_STAFF = "ORGANIZER_STAFF";
  const USERTYPE_USER = "USER";


  const USER_VERIFIED = 1;
  const EMAIL_VERIFIED = 1;

  const DEFAULT_RESET_PASSWORD = "Liveet_12345";

  const PRIVILEDGE_ADMIN_EVENT = "EVENT";
  const PRIVILEDGE_ADMIN_ORGANISER = "ORGANISER";
  const PRIVILEDGE_ADMIN_ACTIVITY_LOG = "ACTIVITY_LOG";
  const PRIVILEDGE_ADMIN_REPORT = "REPORT";
  const PRIVILEDGE_ADMIN_ADMIN = "ADMIN";

  const PRIVILEDGE_ORGANISER_EVENT = "EVENT";
  const PRIVILEDGE_ORGANISER_ORGANISER = "ORGANISER";
  const PRIVILEDGE_ORGANISER_ACTIVITY_LOG = "ACTIVITY_LOG";
  const PRIVILEDGE_ORGANISER_REPORT = "REPORT";

  const ERROR_NOT_FOUND = "Not found";
  const ERROR_EMPTY_DATA = "No more data";

  const IMAGE_PATH = "assets/images/";
  const IMAGE_TYPES_ACCEPTED = ["jpg", "jpeg", "png", "svg"];

  const EVENT_ACCESS_ASSIGNED = "ASSIGNED";
  const EVENT_ACCESS_UNASSIGNED = "UNASSIGNED";
  const EVENT_ACCESS_USED = "USED";

  const EVENT_CAN_TRANSFER_TICKET = "CAN_TRANSFER";
  const EVENT_CAN_NOT_TRANSFER_TICKET = "CAN_NOT_TRANSFER";
  const EVENT_CAN_RECALL_TICKET = "CAN_RECALL";
  const EVENT_CAN_NOT_RECALL_TICKET = "CAN_NOT_RECALL";
  const EVENT_CAN_INVITE = "CAN_INVITE";
  const EVENT_CAN_INVITE_RESTRICTED = "CAN_INVITE_RESTRICTED";
  const EVENT_CAN_NOT_INVITE = "CAN_NOT_INVITE";

  const EVENT_TICKET_USED = "TICKET_USED";
  const EVENT_TICKET_UNUSED = "TICKET_UNUSED";

  const INVITATION_ACCEPT = "ACCEPTED";
  const INVITATION_DECLINED = "DECLINED";
  const INVITATION_PENDING = "PENDING";

  const PAYMENT_TYPE_FREE = "FREE";
  const PAYMENT_TYPE_PAID = "PAID";

  const EVENT_TYPE_PRIVATE = "PRIVATE";
  const EVENT_TYPE_PUBLIC = "PUBLIC ";

  const CREATE_AWS_EVENT_RETRY = 3;

  const INVITEE_CAN_INVITE = "INVITEE_CAN_INVITE";
  const INVITEE_CAN_NOT_INVITE = "INVITEE_CAN_NOT_INVITE";

  const EVENT_TICKET_TRANSFERRED = "TRANSFERRED";
  const EVENT_TICKET_RECALLED = "RECALLED";
  const EVENT_TICKET_ACTIVE = "ACTIVE";

  const NOTIFICATION_ALL_USER = "ALL_USER";
  const NOTIFICATION_ONE_USER = "ONE_USER";
  const NOTIFICATION_USER_GROUP = "USER_GROUP";

  const MOBILE_APP_DOWNLOAD_URL = "https://bit.ly/liveet";
}
